services:

  nginx:
    image: nginx:stable
    volumes:
      - '.:/srv'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - '8080:80'
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    volumes:
      - '.:/srv'
      - ./php.ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"

  db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pa$$}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

volumes:
  db_data:

